sp:
  user-service:
    users: "[{\"id\":99, \"username\":\"abc\",\"password\":\"123\"},{\"id\":100, \"username\":\"def\",\"password\":\"456\"},{\"id\":101, \"username\":\"ghi\",\"password\":\"789\"}]"

spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.64.140
    port: 5672
    username: admin
    password: admin
      
server:
  port: 8101
  
  #添加eureka客户端
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh